version: '3.7'

services:
    app: &default
        build:
            context: ./
            dockerfile: Dockerfile.prod
        ports:
        - "5010:80"
        volumes:
        - ./:/usr/src/app/
        env_file:
        - ./.env.prod

    test: &test
        <<: *default
        command: echo 'yo'

    ci:
        <<: *test
        volumes: []