version: '3.7'

services:
    app: &default
        build:
            context: ./api
            dockerfile: Dockerfile.prod
        ports:
        - "5010:80"
        env_file:
        - ./api/.env.prod

    test: &test
        <<: *default
        command: echo 'yo'

    ci:
        <<: *test
        volumes: []