version: '3.7'

services:
    app: &default
        build:
            context: ./api
            target: prod
            dockerfile: Dockerfile.prod
        ports:
        - "5010:80"
        env_file:
        - ./api/.env.prod

    test: &test
        # command: echo '======== Running tests =========='
        build:
            context: ./api
            target: test
            dockerfile: Dockerfile.prod

    ci:
        <<: *test
        volumes: []