name: Create Vultr VPS instance

on:
  workflow_dispatch:

env:
  VULTR_VPS_REGION: syd
  VULTR_VPS_PLAN: vc2-1c-1gb
  VULTR_VPS_OS_IMAGE: 186 # CentOS
  VULTR_VPS_APP_ID: 17 # Docker
  VULTR_APP_NAME: django-vue-stack
  SSH_EMAIL_ADDRESS: sammykerridge@gmail.com

jobs:
  prepare-ssh-keys:
    name: Create SSH keys
    outputs:
      SSH_KEY_ID: ${{ steps.set-ids.outputs.SSH_KEY_ID }}
    runs-on: ubuntu-latest
    steps:
      # ============== PREPARE =====================
      - name: Install vultr-cli
        uses: techknowlogick/action-vultr@v2
        with:
          token: ${{ secrets.VULTR_API_KEY }}
      
      - name: Checkout server startup script and github scripts
        uses: Bhacaz/checkout-files@v1
        with:
          files: ".github/scripts start-script.sh"
          token: ${{ secrets.GH_ACTIONS_READ_ONLY }}
      
      # ============== SSH KEYS =====================
      - name: Generate + upload new SSH keys
        id: generate-keys
        run: bash -eu .github/scripts/manage-vultr.sh --ssh
        env:
          VULTR_API_KEY: ${{ secrets.VULTR_API_KEY }}

      - name: Read in and mask private key
        id: private-key
        if: hashFiles('key.txt') != ''
        run: |
          PRIVATE_KEY="$(cat key.txt)"

          # mask multiline variable
          while IFS= read -r line ; 
          do
            echo "::add-mask::$line"
          done <<< "$PRIVATE_KEY"

          echo "PRIV_KEY<<EOF" >> $GITHUB_ENV
          echo "$PRIVATE_KEY" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

          echo "::set-output name=PRIVATE_KEY::$PRIVATE_KEY"

      - name: TEST mask
        run: echo "KEY ${{ steps.private-key.outputs.PRIVATE_KEY }}"

      - name: Add SSH private key to Github Secrets
        if: hashFiles('key.txt') != ''
        uses: kerridge/actions-secret-manager@main
        with:
          action: create
          token: ${{ secrets.GH_PA_TOKEN }}
          name: GH_SSH_PRIVATE_KEY
          value: ${{ env.PRIV_KEY }}

      - name: Set output for deploy job to use
        id: set-ids
        run: |
          echo "::set-output name=SSH_KEY_ID::${{ env.SSH_KEY_ID }}"


  prepare-script:
    name: Create Startup Script
    outputs:
      STARTUP_SCRIPT_ID: ${{ steps.set-ids.outputs.STARTUP_SCRIPT_ID }}
    runs-on: ubuntu-latest
    steps:
      # ============== PREPARE =====================
      - name: Install vultr-cli
        uses: techknowlogick/action-vultr@v2
        with:
          token: ${{ secrets.VULTR_API_KEY }}
      
      - name: Checkout server startup script and github scripts
        uses: Bhacaz/checkout-files@v1
        with:
          files: ".github/scripts start-script.sh"
          token: ${{ secrets.GH_ACTIONS_READ_ONLY }}

      # ============== START SCRIPT =====================
      - name: Find and replace <GH_ACCESS_TOKEN> in start script
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "<GH_ACCESS_TOKEN>"
          replace: "${{ secrets.GH_PA_TOKEN }}"
          include: "start-script.sh"

      - name: Find and replace <GH_SSH_URL> in start script
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "<GH_SSH_URL>"
          replace: "${{ github.event.repository.ssh_url }}"
          include: "start-script.sh"

      - name: Find and replace <GH_USERNAME> in start script
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "<GH_USERNAME>"
          replace: "${{ github.repository_owner }}"
          include: "start-script.sh"

      - name: Find and replace <VULTR_APP_NAME> in start script
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "<VULTR_APP_NAME>"
          replace: "${{ env.VULTR_APP_NAME }}"
          include: "start-script.sh"

      - name: Encode and upload start script to Vultr
        run: bash -eu .github/scripts/manage-vultr.sh --start-script
        env:
          VULTR_API_KEY: ${{ secrets.VULTR_API_KEY }}

      - name: Set output for deploy job to use
        id: set-ids
        run: |
          echo "::set-output name=STARTUP_SCRIPT_ID::${{ env.STARTUP_SCRIPT_ID }}"


  deploy:
    name: Deploy Vultr VPS Instance
    needs: ['prepare-ssh-keys', 'prepare-script']
    runs-on: ubuntu-latest
    steps:
      # ============== PREPARE =====================
      - name: Install vultr-cli
        uses: techknowlogick/action-vultr@v2
        with:
          token: ${{ secrets.VULTR_API_KEY }}
      
      - name: Checkout github scripts
        uses: Bhacaz/checkout-files@v1
        with:
          files: ".github/scripts"
          token: ${{ secrets.GH_ACTIONS_READ_ONLY }}
      
      # ============== DEPLOY =====================
      - name: Create instance using vultr-cli
        run: bash -eux .github/scripts/manage-vultr.sh --create-instance
        env:
          VULTR_API_KEY: ${{ secrets.VULTR_API_KEY }}
          STARTUP_SCRIPT_ID: ${{ needs.prepare-script.outputs.STARTUP_SCRIPT_ID }}
          SSH_KEY_ID: ${{ needs.prepare-ssh-keys.outputs.SSH_KEY_ID }}

      - name: Wait for instance start then get IP
        run: bash -eux .github/scripts/manage-vultr.sh --get-ip
        env:
          VULTR_API_KEY: ${{ secrets.VULTR_API_KEY }}

      - name: Add VPS Instance IP to Github Secrets
        uses: kerridge/actions-secret-manager@main
        with:
          action: create
          token: ${{ secrets.GH_PA_TOKEN }}
          name: VULTR_VPS_INSTANCE_IP
          value: ${{ env.VULTR_VPS_INSTANCE_IP }}