name: Deploy API to VPS

on:
  push:
    branches: [ vultr ]
  workflow_dispatch:

env:
  VULTR_VPS_REGION: syd
  VULTR_VPS_PLAN: vc2-1c-1gb
  VULTR_VPS_OS_IMAGE: 186 # CentOS
  VULTR_VPS_APP_ID: 17 # Docker
  VULTR_APP_NAME: django-vue-stack
  SSH_EMAIL_ADDRESS: sammykerridge@gmail.com

  
jobs:
  prepare-script:
    name: Create Startup Script
    outputs:
      STARTUP_SCRIPT_ID: ${{ steps.set-ids.outputs.STARTUP_SCRIPT_ID }}
    runs-on: ubuntu-latest
    steps:
      # ============== PREPARE =====================
      - name: Install vultr-cli
        uses: techknowlogick/action-vultr@v2
        with:
          token: ${{ secrets.VULTR_API_KEY }}
      
      - name: Checkout server startup script and github scripts
        uses: Bhacaz/checkout-files@v1
        with:
          files: ".github/scripts start-script.sh"
          token: ${{ secrets.GH_ACTIONS_READ_ONLY }}

      # ============== START SCRIPT =====================
      - name: Find and replace secrets in start script
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "<GH_ACCESS_TOKEN>"
          replace: "${{ secrets.GH_PA_TOKEN }}"
          include: "start-script.sh"

      - name: Find and replace secrets in start script
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "<GH_SSH_PRIVATE_KEY>"
          replace: "${{ secrets.GH_SSH_PRIVATE_KEY }}"
          include: "start-script.sh"

      - name: Find and replace secrets in start script
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "<GH_SSH_URL>"
          replace: "${{ github.event.repository.ssh_url }}"
          include: "start-script.sh"

      - name: Find and replace secrets in start script
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "<GH_USERNAME>"
          replace: "${{ github.repository_owner }}"
          include: "start-script.sh"

      - name: Find and replace secrets in start script
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "<VULTR_APP_NAME>"
          replace: "LESGOOOO"
          include: "start-script.sh"

      - name: Encode and upload start script to Vultr
        run: bash -eu .github/scripts/manage-vultr.sh --start-script
        env:
          VULTR_API_KEY: ${{ secrets.VULTR_API_KEY }}

      - name: Set output for deploy job to use
        id: set-ids
        run: |
          echo "::set-output name=STARTUP_SCRIPT_ID::${{ env.STARTUP_SCRIPT_ID }}"

  deploy:
    name: Run deploy script via SSH
    runs-on: ubuntu-latest
    steps:
    # - name: Checkout server startup script and github scripts
    #   uses: Bhacaz/checkout-files@v1
    #   with:
    #     files: "test.sh"
    #     token: ${{ secrets.GH_ACTIONS_READ_ONLY }}

    # - name: DO SECRET STUFF
    #   id: private-key
    #   run: |
    #     chmod +x test.sh
    #     VALUE=$(./test.sh)

    #     while IFS= read -r line ; 
    #     do 
    #       echo "::add-mask::$line"
    #     done <<< "$VALUE"

    #     echo "VALUE<<EOF" >> $GITHUB_ENV
    #     echo "$VALUE" >> $GITHUB_ENV
    #     echo "EOF" >> $GITHUB_ENV

    # - name: USE MY THING
    #   uses: kerridge/actions-secret-manager@main
    #   with:
    #     action: create
    #     token: ${{ secrets.GH_PA_TOKEN }}
    #     name: YES_BITCH
    #     value: |
    #       "${{ env.VALUE }}"
        
    # "${{ steps.private-key.outputs.VALUE }}"

    - name: executing remote ssh script using private key
      uses: appleboy/ssh-action@master
      env:
        USER: root
        PROJ_DIR: /home/docker/django-s3-stack
        DEPLOY_SCRIPT: ./test.sh
      with:
        host: ${{ secrets.VULTR_VPS_INSTANCE_IP }}
        username: ${{ env.USER }}
        key: ${{ secrets.GH_SSH_PRIVATE_KEY }}
        script_stop: true
        script: |
          cd ${{ env.PROJ_DIR }}
          ${{ env.DEPLOY_SCRIPT }} ${{ github.event.repository.git_url }} ${{ github.event.repository.name }} ${{ github.repository_owner }} ${{ secrets.GH_ACTIONS_READ_ONLY }}