name: Deploy API to VPS

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build & Push Image"]
    types:
      - completed

env:
  USER: root
  PROJ_DIR: /home/docker/django-s3-stack
  DEPLOY_SCRIPT: ./update-app.sh

jobs:
  deploy:
    name: Run deploy script via SSH
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh script using private key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VULTR_VPS_INSTANCE_IP }}
        username: ${{ env.USER }}
        key: ${{ secrets.GH_SSH_PRIVATE_KEY }}
        script_stop: true
        script: |
          cd ${{ env.PROJ_DIR }}
          git pull origin main
          ${{ env.DEPLOY_SCRIPT }} ${{ github.event.repository.name }}