name: Deploy API to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  VULTR_VPS_REGION: syd
  VULTR_VPS_PLAN: vc2-1c-1gb
  VULTR_VPS_OS_IMAGE: 186 # CentOS
  VULTR_VPS_APP_ID: 17 # Docker
  VULTR_APP_NAME: django-vue-stack
  SSH_EMAIL_ADDRESS: sammykerridge@gmail.com

jobs:
  deploy:
    name: Run deploy script via SSH
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh script using private key
      uses: appleboy/ssh-action@master
      env:
        USER: root
        PROJ_DIR: /home/docker/django-s3-stack
        DEPLOY_SCRIPT: ./update-app.sh
      with:
        host: ${{ secrets.VULTR_VPS_INSTANCE_IP }}
        username: ${{ env.USER }}
        key: ${{ secrets.GH_SSH_PRIVATE_KEY }}
        script_stop: true
        script: |
          cd ${{ env.PROJ_DIR }}
          git pull origin main
          ${{ env.DEPLOY_SCRIPT }} ${{ github.event.repository.name }}