name: Deploy API to VPS

on:
  push:
    branches: [ vultr ]

jobs:
  deploy:
    name: Run deploy script via SSH
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh script using private key
      uses: appleboy/ssh-action@master
      env:
        SERVER_IP: 149.28.180.213
        USER: root
        PROJ_DIR: "/home/docker/proj/django-s3-stack"
      with:
        host: ${{ env.SERVER_IP }}
        username: ${{ env.USER }}
        key: ${{ secrets.WORK_MAC_SSH_PRIVATE }}
        script_stop: true
        envs: PROJ_DIR
        script: |
          cd /home/docker/proj/django-s3-stack
          ls -a