name: Deploy API to VPS

on:
  push:
    branches: [ vultr ]

jobs:
  deploy:
    name: Run deploy script via SSH
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh script using private key
      uses: appleboy/ssh-action@master
      env:
        SERVER_IP: 149.28.180.213
        USER: root
        PROJ_DIR: /home/docker/proj/django-s3-stack
        DEPLOY_SCRIPT: ./test.sh
      with:
        host: ${{ env.SERVER_IP }}
        username: ${{ env.USER }}
        key: ${{ secrets.WORK_MAC_SSH_PRIVATE }}
        script_stop: true
        script: |
          echo ${{ github.GITHUB_SERVER_URL }}/${{ github.GITHUB_REPOSITORY }}.git
          cd ${{ env.PROJ_DIR }}
          ${{ env.DEPLOY_SCRIPT }}

    - name: Check if modified files in project subdirectory
      id: check_files
      run: |
        echo CUSTOM: ${{ github.server_url }}/${{ github.repository }}.git
        echo OWNER: ${{ github.repository_owner }}
        echo GIT URL: ${{ github.event.repository.git_url }}
        echo SERVER: ${{ github.server_url }}
        echo NAME: ${{ github.event.repository.name }}
        
          