name: Deploy API to VPS

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build & Push Image"]
    types:
      - completed

env:
  USER: root
  PROJ_DIR: /home/docker/django-s3-stack
  DEPLOY_SCRIPT: ./update-app.sh
  AWS_STORAGE_BUCKET_NAME: django-vue-stack
  AWS_S3_REGION_NAME: ap-southeast-2
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    name: Run deploy script via SSH
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh script using private key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VULTR_VPS_INSTANCE_IP }}
        username: ${{ env.USER }}
        key: ${{ secrets.GH_SSH_PRIVATE_KEY }}
        script_stop: true
        script: |
          cd ${{ env.PROJ_DIR }}
          git pull origin main
          ${{ env.DEPLOY_SCRIPT }} ${{ github.event.repository.name }}