name: Build Docker container & deploy to Digital Ocean

on:
  schedule:
    - cron: '34 0 * * *'
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/django-s3-stack
  TRIGGER_DIRECTORIES: api .github util

jobs:
  check:
    name: Check for changes
    outputs:
      run_job: ${{ steps.check_files.outputs.run_job }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check if modified files in project subdirectory
        id: check_files
        run: ./util/if_changes_in_subdirectory.sh ${{ env.TRIGGER_DIRECTORIES }}


  build:
    name: Build container
    needs: check
    if: needs.check.outputs.run_job == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # https://github.com/docker/login-action
      - name: Log into Dockerhub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build Docker and publish Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        working-directory: ./api
        with:
          context: .
          file: Dockerfile.prod
          builder: ${{ steps.buildx.outputs.name }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

  publish:
    name: Publish to Digital Ocean
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout app.yaml
        uses: Bhacaz/checkout-files@v1
        with:
          files: api/app.yaml
          token: ${{ secrets.GH_ACTIONS_READ_ONLY }}
        
      - name: Publish app to Digital Ocean
        if: github.event_name != 'pull_request'
        uses: jjst/action-digitalocean-deploy-app@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          app-id: ${{ secrets.DIGITALOCEAN_APP_ID }}
          spec: api/app.yaml
